### ISSUE TITLE
What happened with the old repository?

### ISSUE THREAD

**Issue by trendfischer** [Hedronium/RealCaptcha#2]
I used the old repository to generate captchas and used composer.json to include it in my application. Now, it is renamed and everything (readme, history, fonts) gone. Is there anything about copyrights, a security flaw or else, one should be aware of?

**Comment by omranjamal** [comment]
We're extreme sorry for the inconvenience caused. We're back with the old Repo.

**Comment by trendfischer** [comment]
Thanks :-)
@omranjamal: I still have the commit history till dec'15 if it is missing. I'd like to do a pull request and I wonder, if I should take the short history or the old?

**Comment by omranjamal** [comment]
yeah sure! PR Away! :smile: We really appreciate it. To say the truth, I thought after so little downloads in 3 years its time to kill the old one make the next version. Guess we'll be doing the next version in a separate repo or on a separate branch on this repo.

**Comment by trendfischer** [comment]
Yes, understandable :smile: We use real-captcha in an older application with some sort of older PHP-Version (5.3.3 in RHEL6.x). So real captcha did a good job for the recommondation.

I would appreciate tagging with http://semver.org/ in mind. Works perfectly with composer.json if used correct. In our current release we have a "dev-master"-dependency there, cause the tags weren't up to date.

**Comment by omranjamal** [comment]
Yes, I apologize for that too, this lib was created when I was an absolute noob (I guess it's apparent from the code, One monolithic class; Two classes in one file; Disregard for standards; etc). Hedronium's new stuff follows Semantic Versioning (I hope).

We'll get around to maintaining this soon, when we kids are over with our exams. Till then, thank you for motivating us.

**Comment by trendfischer** [comment]
But for the rescue, this lib was the only useable old captcha-lib that actually worked with composer :wink:
